name: Build and Push Docker Image
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select an action'
        required: true
        default: 'Option 1'
        options:
          - 'Option 1'
          - 'Option 2'
          - 'Option 3'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to ghcr
        run: echo ${{ secrets.DOCKER_PASS }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          # network=host driver-opt needed to push to local registry
          driver-opts: network=host
      - name: Build Docker image
        run: |
              docker buildx build --progress plain \
                --platform linux/amd64,linux/arm64 \
                --tag abhishek3992/myapp:build \
                --tag ghcr.io/alphaace2000/myapp:build \
                --push \
                -f ./Dockerfile .
