name: Build and Push Docker Image
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select an action'
        required: true
        default: 'Option 1'
        options:
          - 'Option 1'
          - 'Option 2'
          - 'Option 3'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create a new Buildx builder
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect mybuilder --bootstrap
      - name: Build Docker image
        run: |
              docker buildx build \
                --progress plain \
                --platform linux/amd64,linux/arm64 \
                --tag myapp:build \
                -f ./Dockerfile .
      - name: List Docker images
        run: docker images
      - name: push
        run: |
              docker push abhishek3992/myapp:build
